// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function toJs(cashier) {
  return {
          name: cashier[/* name */0],
          pin: cashier[/* pin */1]
        };
}

var New = /* module */[/* toJs */toJs];

function fromJs(cashierJs) {
  return /* record */[
          /* id */cashierJs._id,
          /* name */cashierJs.name,
          /* pin */cashierJs.pin
        ];
}

function toJsWithRev(id, rev, cashier) {
  return {
          _id: id,
          _rev: rev,
          name: cashier[/* name */1],
          pin: cashier[/* pin */2]
        };
}

function toJs$1(cashier) {
  return {
          _id: cashier[/* id */0],
          name: cashier[/* name */1],
          pin: cashier[/* pin */2]
        };
}

exports.New = New;
exports.fromJs = fromJs;
exports.toJsWithRev = toJsWithRev;
exports.toJs = toJs$1;
/* No side effect */
