// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

function now() {
  return Date.now();
}

function toDisplayDate(t) {
  return new Date(t).toDateString();
}

function toDisplayTime(t) {
  return new Date(t).toTimeString();
}

function toShortTime(t) {
  var d = new Date(t);
  var armyHours = d.getHours() | 0;
  var isPm = +(armyHours % 12 === 0);
  var hoursPossibleZero = isPm !== 0 ? armyHours - 12 | 0 : armyHours;
  var match = +(hoursPossibleZero === 0);
  var hours = match !== 0 ? 12 : hoursPossibleZero;
  var minutes = d.getMinutes() | 0;
  var match$1 = +(minutes < 10);
  var leadingZero = match$1 !== 0 ? "0" : "";
  var ampm = isPm !== 0 ? "PM" : "AM";
  return String(hours) + (":" + (leadingZero + (String(minutes) + (" " + ampm))));
}

function toISODate(t) {
  return Caml_array.caml_array_get(new Date(t).toISOString().split("T"), 0);
}

function toDisplay(t) {
  return new Date(t).toString();
}

function oneMonthBefore(t) {
  return t - 86400000.0 * 30.44;
}

function addDays(d, t) {
  return t + 86400000.0 * d;
}

function startOfDay(d) {
  var jsDate = new Date(d);
  jsDate.setHours(0, 0, 0);
  return jsDate.getTime();
}

function endOfDay(d) {
  var jsDate = new Date(d);
  jsDate.setHours(23, 59, 59);
  return jsDate.getTime();
}

function toFloat(formattedDate) {
  return new Date(formattedDate).getTime();
}

function isValid(formattedDate) {
  var t = new Date(formattedDate).getTime();
  var match = new Date(t).toString();
  if (match === "Invalid Date") {
    return /* false */0;
  } else {
    return /* true */1;
  }
}

var day = 86400000.0;

exports.now = now;
exports.day = day;
exports.toDisplayDate = toDisplayDate;
exports.toDisplayTime = toDisplayTime;
exports.toShortTime = toShortTime;
exports.toISODate = toISODate;
exports.toDisplay = toDisplay;
exports.oneMonthBefore = oneMonthBefore;
exports.addDays = addDays;
exports.startOfDay = startOfDay;
exports.endOfDay = endOfDay;
exports.toFloat = toFloat;
exports.isValid = isValid;
/* No side effect */
