// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var $$Date = require("./Date.js");
var Jest = require("bs-jest/lib/js/src/jest.js");

describe("Date functions", (function () {
        describe("when converting from date float to sortable date", (function () {
                describe("and float is a valid date", (function () {
                        return Jest.test("it should return the corresponding date in YYYY-MM-DD format", (function () {
                                      return Jest.Expect[/* toEqual */12]("2018-03-29", Jest.Expect[/* expect */0]($$Date.toISODate(1522350507000)));
                                    }));
                      }));
                return /* () */0;
              }));
        describe("when getting the start of the day", (function () {
                return Jest.test("it should return the corresponding date at midnight", (function () {
                              return Jest.Expect[/* toEqual */12](1522281600000, Jest.Expect[/* expect */0]($$Date.startOfDay(1522350507000)));
                            }));
              }));
        describe("when getting the end of the day", (function () {
                return Jest.test("it should return the corresponding date at 11:59:59", (function () {
                              return Jest.Expect[/* toEqual */12](1522367999000, Jest.Expect[/* expect */0]($$Date.endOfDay(1522350507000)));
                            }));
              }));
        describe("when converting", (function () {
                var formatted = "Thu Mar 29 2018 13:08:27 GMT-0600 (CST)";
                describe("a float to a short time", (function () {
                        return Jest.test("it should give only the time in short format", (function () {
                                      return Jest.Expect[/* toEqual */12]("12:03 PM", Jest.Expect[/* expect */0]($$Date.toShortTime(1522433031521)));
                                    }));
                      }));
                describe("a formatted date/time to a float", (function () {
                        return Jest.test("it should parse the string to the correct float", (function () {
                                      return Jest.Expect[/* toEqual */12](1522350507000, Jest.Expect[/* expect */0]($$Date.toFloat(formatted)));
                                    }));
                      }));
                describe("a float to a formatted date/time", (function () {
                        return Jest.test("it should format the float to a human readable format", (function () {
                                      return Jest.Expect[/* toEqual */12](formatted, Jest.Expect[/* expect */0]($$Date.toDisplay(1522350507000)));
                                    }));
                      }));
                return /* () */0;
              }));
        describe("when validating", (function () {
                describe("an invalid date/time to a float", (function () {
                        return Jest.test("it should be false", (function () {
                                      return Jest.Expect[/* toEqual */12](/* false */0, Jest.Expect[/* expect */0]($$Date.isValid("Thu Mar 32 2018 13:08:27 GMT-0600 (CST)")));
                                    }));
                      }));
                describe("a valid date/time to a float", (function () {
                        return Jest.test("it should be true", (function () {
                                      return Jest.Expect[/* toEqual */12](/* true */1, Jest.Expect[/* expect */0]($$Date.isValid("Thu Mar 29 2018 13:08:27 GMT-0600 (CST)")));
                                    }));
                      }));
                return /* () */0;
              }));
        describe("when getting the date one month before", (function () {
                return Jest.test("it should give a date that is 30.44 days prior", (function () {
                              return Jest.Expect[/* toEqual */12]("Tue Feb 27 2018", Jest.Expect[/* expect */0]($$Date.toDisplayDate($$Date.oneMonthBefore(1522350507000))));
                            }));
              }));
        return /* () */0;
      }));

var unixTime = 1522350507000;

var formatted = "Thu Mar 29 2018 13:08:27 GMT-0600 (CST)";

exports.unixTime = unixTime;
exports.formatted = formatted;
/*  Not a pure module */
