// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function mapToJs(discount) {
  return {
          name: discount[/* name */0],
          percent: discount[/* percent */1]
        };
}

var NewDiscount = /* module */[/* mapToJs */mapToJs];

function mapFromJs(discountJs) {
  return /* record */[
          /* id */discountJs._id,
          /* name */discountJs.name,
          /* percent */discountJs.percent
        ];
}

function mapToJsWithRev(id, rev, discount) {
  return {
          _id: id,
          _rev: rev,
          name: discount[/* name */1],
          percent: discount[/* percent */2]
        };
}

function mapToJs$1(discount) {
  return {
          name: discount[/* name */1],
          percent: discount[/* percent */2]
        };
}

exports.NewDiscount = NewDiscount;
exports.mapFromJs = mapFromJs;
exports.mapToJsWithRev = mapToJsWithRev;
exports.mapToJs = mapToJs$1;
/* No side effect */
