// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function toJs(expenseType) {
  return {
          name: expenseType[/* name */0]
        };
}

var New = /* module */[/* toJs */toJs];

function fromJs(expenseTypeJs) {
  return /* record */[
          /* id */expenseTypeJs._id,
          /* name */expenseTypeJs.name
        ];
}

function toJsWithRev(id, rev, expenseType) {
  return {
          _id: id,
          _rev: rev,
          name: expenseType[/* name */1]
        };
}

function toJs$1(expenseType) {
  return {
          _id: expenseType[/* id */0],
          name: expenseType[/* name */1]
        };
}

exports.New = New;
exports.fromJs = fromJs;
exports.toJsWithRev = toJsWithRev;
exports.toJs = toJs$1;
/* No side effect */
