// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Group = require("./Group.js");

function buildSale(name, taxRate) {
  return /* record */[
          /* sku */name,
          /* salePrice */1234,
          /* productName */name,
          /* taxRate */taxRate,
          /* suggestedPrice */0,
          /* discounts : [] */0
        ];
}

describe("The group by functions", (function () {
        describe("when grouping items in a list by some key", (function () {
                describe("where items are simple ints", (function () {
                        var groups = Group.by((function (x) {
                                return String(x);
                              }), /* :: */[
                              1,
                              /* :: */[
                                2,
                                /* :: */[
                                  3,
                                  /* :: */[
                                    1,
                                    /* :: */[
                                      2,
                                      /* :: */[
                                        3,
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]);
                        return Jest.test("it should group the ints", (function () {
                                      return Jest.Expect[/* toEqual */12](/* :: */[
                                                  /* record */[
                                                    /* key */"1",
                                                    /* value : :: */[
                                                      1,
                                                      /* :: */[
                                                        1,
                                                        /* [] */0
                                                      ]
                                                    ]
                                                  ],
                                                  /* :: */[
                                                    /* record */[
                                                      /* key */"2",
                                                      /* value : :: */[
                                                        2,
                                                        /* :: */[
                                                          2,
                                                          /* [] */0
                                                        ]
                                                      ]
                                                    ],
                                                    /* :: */[
                                                      /* record */[
                                                        /* key */"3",
                                                        /* value : :: */[
                                                          3,
                                                          /* :: */[
                                                            3,
                                                            /* [] */0
                                                          ]
                                                        ]
                                                      ],
                                                      /* [] */0
                                                    ]
                                                  ]
                                                ], Jest.Expect[/* expect */0](groups));
                                    }));
                      }));
                describe("when getting a group of sales by taxRate", (function () {
                        var groups = Group.by((function (x) {
                                return String(x[/* taxRate */3]);
                              }), /* :: */[
                              /* record */[
                                /* sku */"bread",
                                /* salePrice */1234,
                                /* productName */"bread",
                                /* taxRate */15,
                                /* suggestedPrice */0,
                                /* discounts : [] */0
                              ],
                              /* :: */[
                                /* record */[
                                  /* sku */"bread",
                                  /* salePrice */1234,
                                  /* productName */"bread",
                                  /* taxRate */10,
                                  /* suggestedPrice */0,
                                  /* discounts : [] */0
                                ],
                                /* :: */[
                                  /* record */[
                                    /* sku */"bread",
                                    /* salePrice */1234,
                                    /* productName */"bread",
                                    /* taxRate */15,
                                    /* suggestedPrice */0,
                                    /* discounts : [] */0
                                  ],
                                  /* :: */[
                                    /* record */[
                                      /* sku */"bread",
                                      /* salePrice */1234,
                                      /* productName */"bread",
                                      /* taxRate */10,
                                      /* suggestedPrice */0,
                                      /* discounts : [] */0
                                    ],
                                    /* :: */[
                                      /* record */[
                                        /* sku */"cheese",
                                        /* salePrice */1234,
                                        /* productName */"cheese",
                                        /* taxRate */15,
                                        /* suggestedPrice */0,
                                        /* discounts : [] */0
                                      ],
                                      /* :: */[
                                        /* record */[
                                          /* sku */"cheese",
                                          /* salePrice */1234,
                                          /* productName */"cheese",
                                          /* taxRate */10,
                                          /* suggestedPrice */0,
                                          /* discounts : [] */0
                                        ],
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]);
                        return Jest.test("it should group them correctly", (function () {
                                      return Jest.Expect[/* toEqual */12](/* :: */[
                                                  /* record */[
                                                    /* key */"10",
                                                    /* value : :: */[
                                                      /* record */[
                                                        /* sku */"bread",
                                                        /* salePrice */1234,
                                                        /* productName */"bread",
                                                        /* taxRate */10,
                                                        /* suggestedPrice */0,
                                                        /* discounts : [] */0
                                                      ],
                                                      /* :: */[
                                                        /* record */[
                                                          /* sku */"bread",
                                                          /* salePrice */1234,
                                                          /* productName */"bread",
                                                          /* taxRate */10,
                                                          /* suggestedPrice */0,
                                                          /* discounts : [] */0
                                                        ],
                                                        /* :: */[
                                                          /* record */[
                                                            /* sku */"cheese",
                                                            /* salePrice */1234,
                                                            /* productName */"cheese",
                                                            /* taxRate */10,
                                                            /* suggestedPrice */0,
                                                            /* discounts : [] */0
                                                          ],
                                                          /* [] */0
                                                        ]
                                                      ]
                                                    ]
                                                  ],
                                                  /* :: */[
                                                    /* record */[
                                                      /* key */"15",
                                                      /* value : :: */[
                                                        /* record */[
                                                          /* sku */"bread",
                                                          /* salePrice */1234,
                                                          /* productName */"bread",
                                                          /* taxRate */15,
                                                          /* suggestedPrice */0,
                                                          /* discounts : [] */0
                                                        ],
                                                        /* :: */[
                                                          /* record */[
                                                            /* sku */"bread",
                                                            /* salePrice */1234,
                                                            /* productName */"bread",
                                                            /* taxRate */15,
                                                            /* suggestedPrice */0,
                                                            /* discounts : [] */0
                                                          ],
                                                          /* :: */[
                                                            /* record */[
                                                              /* sku */"cheese",
                                                              /* salePrice */1234,
                                                              /* productName */"cheese",
                                                              /* taxRate */15,
                                                              /* suggestedPrice */0,
                                                              /* discounts : [] */0
                                                            ],
                                                            /* [] */0
                                                          ]
                                                        ]
                                                      ]
                                                    ],
                                                    /* [] */0
                                                  ]
                                                ], Jest.Expect[/* expect */0](groups));
                                    }));
                      }));
                describe("where items are sales", (function () {
                        var groups = Group.by((function (x) {
                                return x[/* productName */2];
                              }), /* :: */[
                              /* record */[
                                /* sku */"bread",
                                /* salePrice */1234,
                                /* productName */"bread",
                                /* taxRate */15,
                                /* suggestedPrice */0,
                                /* discounts : [] */0
                              ],
                              /* :: */[
                                /* record */[
                                  /* sku */"bread",
                                  /* salePrice */1234,
                                  /* productName */"bread",
                                  /* taxRate */15,
                                  /* suggestedPrice */0,
                                  /* discounts : [] */0
                                ],
                                /* :: */[
                                  /* record */[
                                    /* sku */"bread",
                                    /* salePrice */1234,
                                    /* productName */"bread",
                                    /* taxRate */15,
                                    /* suggestedPrice */0,
                                    /* discounts : [] */0
                                  ],
                                  /* :: */[
                                    /* record */[
                                      /* sku */"bread",
                                      /* salePrice */1234,
                                      /* productName */"bread",
                                      /* taxRate */15,
                                      /* suggestedPrice */0,
                                      /* discounts : [] */0
                                    ],
                                    /* :: */[
                                      /* record */[
                                        /* sku */"cheese",
                                        /* salePrice */1234,
                                        /* productName */"cheese",
                                        /* taxRate */15,
                                        /* suggestedPrice */0,
                                        /* discounts : [] */0
                                      ],
                                      /* :: */[
                                        /* record */[
                                          /* sku */"cheese",
                                          /* salePrice */1234,
                                          /* productName */"cheese",
                                          /* taxRate */15,
                                          /* suggestedPrice */0,
                                          /* discounts : [] */0
                                        ],
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]);
                        return Jest.test("it should group sales by product name", (function () {
                                      return Jest.Expect[/* toEqual */12](/* :: */[
                                                  /* record */[
                                                    /* key */"bread",
                                                    /* value : :: */[
                                                      /* record */[
                                                        /* sku */"bread",
                                                        /* salePrice */1234,
                                                        /* productName */"bread",
                                                        /* taxRate */15,
                                                        /* suggestedPrice */0,
                                                        /* discounts : [] */0
                                                      ],
                                                      /* :: */[
                                                        /* record */[
                                                          /* sku */"bread",
                                                          /* salePrice */1234,
                                                          /* productName */"bread",
                                                          /* taxRate */15,
                                                          /* suggestedPrice */0,
                                                          /* discounts : [] */0
                                                        ],
                                                        /* :: */[
                                                          /* record */[
                                                            /* sku */"bread",
                                                            /* salePrice */1234,
                                                            /* productName */"bread",
                                                            /* taxRate */15,
                                                            /* suggestedPrice */0,
                                                            /* discounts : [] */0
                                                          ],
                                                          /* :: */[
                                                            /* record */[
                                                              /* sku */"bread",
                                                              /* salePrice */1234,
                                                              /* productName */"bread",
                                                              /* taxRate */15,
                                                              /* suggestedPrice */0,
                                                              /* discounts : [] */0
                                                            ],
                                                            /* [] */0
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ],
                                                  /* :: */[
                                                    /* record */[
                                                      /* key */"cheese",
                                                      /* value : :: */[
                                                        /* record */[
                                                          /* sku */"cheese",
                                                          /* salePrice */1234,
                                                          /* productName */"cheese",
                                                          /* taxRate */15,
                                                          /* suggestedPrice */0,
                                                          /* discounts : [] */0
                                                        ],
                                                        /* :: */[
                                                          /* record */[
                                                            /* sku */"cheese",
                                                            /* salePrice */1234,
                                                            /* productName */"cheese",
                                                            /* taxRate */15,
                                                            /* suggestedPrice */0,
                                                            /* discounts : [] */0
                                                          ],
                                                          /* [] */0
                                                        ]
                                                      ]
                                                    ],
                                                    /* [] */0
                                                  ]
                                                ], Jest.Expect[/* expect */0](groups));
                                    }));
                      }));
                return /* () */0;
              }));
        return /* () */0;
      }));

exports.buildSale = buildSale;
/*  Not a pure module */
