// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function by(keyFn, list) {
  return List.map((function (param) {
                return /* record */[
                        /* key */param[0],
                        /* value */param[1]
                      ];
              }), $$Array.to_list(Js_dict.entries(Belt_List.reduce(list, { }, (function (acc, cur) {
                            var key = Curry._1(keyFn, cur);
                            var value = acc[key];
                            var items = value !== undefined ? value : /* [] */0;
                            acc[key] = List.concat(/* :: */[
                                  items,
                                  /* :: */[
                                    /* :: */[
                                      cur,
                                      /* [] */0
                                    ],
                                    /* [] */0
                                  ]
                                ]);
                            return acc;
                          })))));
}

exports.by = by;
/* Js_dict Not a pure module */
