// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function convertFloatOption(d) {
  if (d == null) {
    return /* None */0;
  } else {
    return [d];
  }
}

function convertIntOption(d) {
  if (d == null) {
    return /* None */0;
  } else {
    return [d];
  }
}

function convertStringOption(s) {
  if (s == null) {
    return /* None */0;
  } else {
    return [s];
  }
}

function convertDate(d) {
  return d;
}

exports.convertFloatOption = convertFloatOption;
exports.convertIntOption = convertIntOption;
exports.convertStringOption = convertStringOption;
exports.convertDate = convertDate;
/* No side effect */
