// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function toJs(log) {
  return {
          logType: log[/* logType */0],
          level: log[/* level */1],
          message: log[/* message */2],
          payload: log[/* payload */3]
        };
}

var New = /* module */[/* toJs */toJs];

function fromJs(logJs) {
  return /* record */[
          /* id */logJs._id,
          /* logType */logJs.logType,
          /* level */logJs.level,
          /* message */logJs.message,
          /* payload */logJs.payload
        ];
}

function toJs$1(log) {
  return {
          _id: log[/* id */0],
          logType: log[/* logType */1],
          level: log[/* level */2],
          message: log[/* message */3],
          payload: log[/* payload */4]
        };
}

exports.New = New;
exports.fromJs = fromJs;
exports.toJs = toJs$1;
/* No side effect */
