// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function cleanNonNumeric(n) {
  return n.replace((/\D/g), "");
}

function toDisplay(t) {
  return Curry._1(Printf.sprintf(/* Format */[
                  /* Float */Block.__(8, [
                      /* Float_f */0,
                      /* No_padding */0,
                      /* Lit_precision */[2],
                      /* End_of_format */0
                    ]),
                  "%.2f"
                ]), t / 100.0);
}

function times100(n) {
  return n * 100.0;
}

function toT(str) {
  if (str === "") {
    return 0;
  } else {
    return Caml_format.caml_float_of_string(str) * 100.0 | 0;
  }
}

exports.cleanNonNumeric = cleanNonNumeric;
exports.toDisplay = toDisplay;
exports.times100 = times100;
exports.toT = toT;
/* No side effect */
