// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Money = require("./Money.js");

describe("Money functions", (function () {
        describe("when converting a mixed number to money display", (function () {
                return Jest.test("it should show the amount with decimal places", (function () {
                              var display = Money.toDisplay(123456);
                              return Jest.Expect[/* toEqual */12]("L.1234.56", Jest.Expect[/* expect */0](display));
                            }));
              }));
        describe("when converting a closed number to money display", (function () {
                return Jest.test("it should show the amount with decimal places", (function () {
                              var display = Money.toDisplay(1000);
                              return Jest.Expect[/* toEqual */12]("L.10.00", Jest.Expect[/* expect */0](display));
                            }));
              }));
        describe("when converting a valid money display string to int", (function () {
                return Jest.test("it should return the correct int", (function () {
                              var amount = Money.toT("L.10.00");
                              return Jest.Expect[/* toEqual */12](1000, Jest.Expect[/* expect */0](amount));
                            }));
              }));
        describe("when converting an invalid money display string to int", (function () {
                return Jest.test("it should return the correct int", (function () {
                              var amount = Money.toT("N.10.000");
                              return Jest.Expect[/* toEqual */12](10000, Jest.Expect[/* expect */0](amount));
                            }));
              }));
        return /* () */0;
      }));

/*  Not a pure module */
