// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Tax = require("./Tax.js");
var JsUtils = require("./JsUtils.js");

function mapOrderItemFromJs(itemJs) {
  return /* record */[
          /* sku */itemJs.sku,
          /* name */itemJs.name,
          /* suggestedPrice */itemJs.suggestedPrice,
          /* addedOn */JsUtils.convertDate(itemJs.addedOn),
          /* salePrice */itemJs.salePrice,
          /* taxCalculation */Tax.Calculation[/* toMethod */1](itemJs.taxCalculation)
        ];
}

function orderItemToJs(orderItem) {
  return {
          sku: orderItem[/* sku */0],
          name: orderItem[/* name */1],
          suggestedPrice: orderItem[/* suggestedPrice */2],
          addedOn: orderItem[/* addedOn */3],
          salePrice: orderItem[/* salePrice */4],
          taxCalculation: Tax.Calculation[/* toDelimitedString */0](orderItem[/* taxCalculation */5])
        };
}

exports.mapOrderItemFromJs = mapOrderItemFromJs;
exports.orderItemToJs = orderItemToJs;
/* No side effect */
