// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var PaymentMethod = require("./PaymentMethod.js");

function toJs(p) {
  return {
          subTotal: p[/* subTotal */0],
          discount: p[/* discount */1],
          tax: p[/* tax */2],
          total: p[/* total */3],
          on: p[/* on */4],
          by: p[/* by */5],
          externalId: p[/* externalId */6],
          paymentMethod: PaymentMethod.toJs(p[/* method */7])
        };
}

function fromJs(p) {
  return /* record */[
          /* subTotal */p.subTotal,
          /* discount */p.discount,
          /* tax */p.tax,
          /* total */p.total,
          /* on */p.on,
          /* by */p.by,
          /* externalId */p.externalId,
          /* method */PaymentMethod.fromJs(p.paymentMethod)
        ];
}

exports.toJs = toJs;
exports.fromJs = fromJs;
/* No side effect */
