// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/lib/js/src/jest.js");
var Paid = require("./Paid.js");

describe("Paid module", (function () {
        describe("when mapping from js", (function () {
                describe("with a card method", (function () {
                        var paid_006 = /* externalId : Some */["id"];
                        var paid_007 = /* method : record */[
                          /* name */"card",
                          /* hasExternalId : true */1
                        ];
                        var paid = /* record */[
                          /* subTotal */12300,
                          /* discount */12300,
                          /* tax */12300,
                          /* total */12300,
                          /* on */412341324,
                          /* by */"Byron",
                          paid_006,
                          paid_007
                        ];
                        return Jest.test("he method should still be card", (function () {
                                      var js = Paid.toJs(paid);
                                      var p = Paid.fromJs(js);
                                      return Jest.Expect[/* toEqual */12]("card", Jest.Expect[/* expect */0](p[/* method */7][/* name */0]));
                                    }));
                      }));
                describe("with cash method", (function () {
                        var paid_006 = /* externalId : Some */["id"];
                        var paid_007 = /* method : record */[
                          /* name */"cash",
                          /* hasExternalId : true */1
                        ];
                        var paid = /* record */[
                          /* subTotal */12300,
                          /* discount */12300,
                          /* tax */12300,
                          /* total */12300,
                          /* on */412341324,
                          /* by */"Byron",
                          paid_006,
                          paid_007
                        ];
                        return Jest.test("the method should still be cash", (function () {
                                      var js = Paid.toJs(paid);
                                      var p = Paid.fromJs(js);
                                      return Jest.Expect[/* toEqual */12]("cash", Jest.Expect[/* expect */0](p[/* method */7][/* name */0]));
                                    }));
                      }));
                return /* () */0;
              }));
        return /* () */0;
      }));

/*  Not a pure module */
