// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var PaymentMethod = require("./PaymentMethod.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function toJs(p) {
  return {
          subTotal: p[/* subTotal */0],
          discount: p[/* discount */1],
          tax: p[/* tax */2],
          total: p[/* total */3],
          on: p[/* on */4],
          by: p[/* by */5],
          externalId: Js_null_undefined.fromOption(p[/* externalId */6]),
          paymentMethod: PaymentMethod.toJs(p[/* method */7])
        };
}

function fromJs(p) {
  return /* record */[
          /* subTotal */p.subTotal,
          /* discount */p.discount,
          /* tax */p.tax,
          /* total */p.total,
          /* on */p.on,
          /* by */p.by,
          /* externalId */Js_primitive.null_undefined_to_opt(p.externalId),
          /* method */PaymentMethod.fromJs(p.paymentMethod)
        ];
}

exports.toJs = toJs;
exports.fromJs = fromJs;
/* No side effect */
