// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function toJs(p) {
  return {
          subTotal: p[/* subTotal */0],
          discount: p[/* discount */1],
          tax: p[/* tax */2],
          total: p[/* total */3],
          on: p[/* on */4],
          by: p[/* by */5]
        };
}

function fromJs(p) {
  return /* record */[
          /* subTotal */p.subTotal,
          /* discount */p.discount,
          /* tax */p.tax,
          /* total */p.total,
          /* on */p.on,
          /* by */p.by
        ];
}

exports.toJs = toJs;
exports.fromJs = fromJs;
/* No side effect */
