// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function toJs(t) {
  return {
          name: t[/* name */0],
          hasExternalId: t[/* hasExternalId */1]
        };
}

function fromJs(t) {
  return /* record */[
          /* name */t.name,
          /* hasExternalId */t.hasExternalId
        ];
}

var $$default = /* record */[
  /* name */"Default",
  /* hasExternalId : false */0
];

exports.toJs = toJs;
exports.fromJs = fromJs;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* No side effect */
