// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


var $$default = /* record */[
  /* name */"paymentMethod.cash",
  /* hasExternalId : false */0
];

function toJs(t) {
  return {
          name: t[/* name */0],
          hasExternalId: t[/* hasExternalId */1]
        };
}

function fromJs(t) {
  if (t == null) {
    return $$default;
  } else {
    return /* record */[
            /* name */t.name,
            /* hasExternalId */t.hasExternalId
          ];
  }
}

var tempAllPaymentMethods_001 = /* :: */[
  /* record */[
    /* name */"paymentMethod.card",
    /* hasExternalId : true */1
  ],
  /* [] */0
];

var tempAllPaymentMethods = /* :: */[
  $$default,
  tempAllPaymentMethods_001
];

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.toJs = toJs;
exports.fromJs = fromJs;
exports.tempAllPaymentMethods = tempAllPaymentMethods;
/* No side effect */
