// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Caml_format = require("bs-platform/lib/js/caml_format.js");

function cleanNonNumeric(n) {
  return n.replace((/\D/g), "");
}

function toDisplay(t) {
  var n = String(t);
  return n.replace((/\D/g), "") + "%";
}

function toFloat(t) {
  return t / 100;
}

function calculate(percent, num) {
  return num * (percent / 100) | 0;
}

function toT(str) {
  var s = str.replace((/\D/g), "");
  if (s === "") {
    return 0;
  } else {
    return Caml_format.caml_int_of_string(s);
  }
}

exports.cleanNonNumeric = cleanNonNumeric;
exports.toDisplay = toDisplay;
exports.toFloat = toFloat;
exports.calculate = calculate;
exports.toT = toT;
/* No side effect */
