// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Tax = require("./Tax.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

function mapToJs(prod) {
  return {
          sku: prod[/* sku */0],
          name: prod[/* name */1],
          suggestedPrice: prod[/* suggestedPrice */3],
          tags: $$Array.of_list(prod[/* tags */2]),
          taxCalculation: Tax.Calculation[/* toDelimitedString */0](prod[/* taxCalculation */4])
        };
}

var NewProduct = /* module */[/* mapToJs */mapToJs];

function mapFromJs(prodJs) {
  return /* record */[
          /* id */prodJs._id,
          /* sku */prodJs.sku,
          /* name */prodJs.name,
          /* tags */prodJs.tags,
          /* suggestedPrice */prodJs.suggestedPrice,
          /* taxCalculation */Tax.Calculation[/* toMethod */1](prodJs.taxCalculation)
        ];
}

function mapToJsWithRev(id, rev, prod) {
  return {
          _id: id,
          _rev: rev,
          sku: prod[/* sku */1],
          name: prod[/* name */2],
          suggestedPrice: prod[/* suggestedPrice */4],
          tags: prod[/* tags */3],
          taxCalculation: Tax.Calculation[/* toDelimitedString */0](prod[/* taxCalculation */5])
        };
}

function mapToJs$1(prod) {
  return mapToJsWithRev(prod[/* id */0], /* None */0, prod);
}

function getTags(products) {
  var tagArrArr = List.map((function (p) {
          return p[/* tags */3];
        }), products);
  var allTags = List.flatten(tagArrArr);
  return List.sort_uniq($$String.compare, allTags);
}

function filterProducts(tag, products) {
  return List.filter((function (p) {
                  return List.exists((function (t) {
                                return +(t === tag);
                              }), p[/* tags */3]);
                }))(products);
}

exports.NewProduct = NewProduct;
exports.mapFromJs = mapFromJs;
exports.mapToJsWithRev = mapToJsWithRev;
exports.mapToJs = mapToJs$1;
exports.getTags = getTags;
exports.filterProducts = filterProducts;
/* No side effect */
