// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/lib/js/src/jest.js");
var ProductGroup = require("./ProductGroup.js");

function buildSale(sku, price, taxRate) {
  return /* record */[
          /* sku */sku,
          /* salePrice */price,
          /* productName */"test",
          /* taxRate */taxRate,
          /* suggestedPrice */0,
          /* discounts : [] */0
        ];
}

describe("The product group module", (function () {
        describe("when converting a list of sales to a grouped list products", (function () {
                describe("where items are normal sales", (function () {
                        var bread = /* record */[
                          /* sku */"bread",
                          /* salePrice */100,
                          /* productName */"test",
                          /* taxRate */15,
                          /* suggestedPrice */0,
                          /* discounts : [] */0
                        ];
                        var cheese = /* record */[
                          /* sku */"cheese",
                          /* salePrice */100,
                          /* productName */"test",
                          /* taxRate */15,
                          /* suggestedPrice */0,
                          /* discounts : [] */0
                        ];
                        var sales_001 = /* :: */[
                          bread,
                          /* :: */[
                            bread,
                            /* :: */[
                              cheese,
                              /* :: */[
                                cheese,
                                /* [] */0
                              ]
                            ]
                          ]
                        ];
                        var sales = /* :: */[
                          bread,
                          sales_001
                        ];
                        var groupedSales = ProductGroup.fromSalesList(sales);
                        return Jest.test("it should calculate the subtotal of all items", (function () {
                                      return Jest.Expect[/* toEqual */12](/* :: */[
                                                  /* record */[
                                                    /* sku */"bread",
                                                    /* productName */"test",
                                                    /* taxRate */15,
                                                    /* salePrice */100,
                                                    /* quantity */3,
                                                    /* subTotal */300,
                                                    /* tax */45,
                                                    /* total */345
                                                  ],
                                                  /* :: */[
                                                    /* record */[
                                                      /* sku */"cheese",
                                                      /* productName */"test",
                                                      /* taxRate */15,
                                                      /* salePrice */100,
                                                      /* quantity */2,
                                                      /* subTotal */200,
                                                      /* tax */30,
                                                      /* total */230
                                                    ],
                                                    /* [] */0
                                                  ]
                                                ], Jest.Expect[/* expect */0](groupedSales));
                                    }));
                      }));
                describe("where items have changed price or taxRate", (function () {
                        var bread1 = /* record */[
                          /* sku */"bread",
                          /* salePrice */1000,
                          /* productName */"test",
                          /* taxRate */15,
                          /* suggestedPrice */0,
                          /* discounts : [] */0
                        ];
                        var bread2 = /* record */[
                          /* sku */"bread",
                          /* salePrice */1000,
                          /* productName */"test",
                          /* taxRate */10,
                          /* suggestedPrice */0,
                          /* discounts : [] */0
                        ];
                        var cheese1 = /* record */[
                          /* sku */"cheese",
                          /* salePrice */500,
                          /* productName */"test",
                          /* taxRate */15,
                          /* suggestedPrice */0,
                          /* discounts : [] */0
                        ];
                        var cheese2 = /* record */[
                          /* sku */"cheese",
                          /* salePrice */1000,
                          /* productName */"test",
                          /* taxRate */15,
                          /* suggestedPrice */0,
                          /* discounts : [] */0
                        ];
                        var sales_001 = /* :: */[
                          bread1,
                          /* :: */[
                            bread1,
                            /* :: */[
                              cheese2,
                              /* :: */[
                                cheese2,
                                /* :: */[
                                  cheese1,
                                  /* :: */[
                                    cheese1,
                                    /* :: */[
                                      bread2,
                                      /* :: */[
                                        bread2,
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ];
                        var sales = /* :: */[
                          bread1,
                          sales_001
                        ];
                        var groupedSales = ProductGroup.fromSalesList(sales);
                        return Jest.test("it should calculate the subtotal of all items", (function () {
                                      return Jest.Expect[/* toEqual */12](/* :: */[
                                                  /* record */[
                                                    /* sku */"bread",
                                                    /* productName */"test",
                                                    /* taxRate */15,
                                                    /* salePrice */1000,
                                                    /* quantity */3,
                                                    /* subTotal */3000,
                                                    /* tax */450,
                                                    /* total */3450
                                                  ],
                                                  /* :: */[
                                                    /* record */[
                                                      /* sku */"cheese",
                                                      /* productName */"test",
                                                      /* taxRate */15,
                                                      /* salePrice */1000,
                                                      /* quantity */2,
                                                      /* subTotal */2000,
                                                      /* tax */300,
                                                      /* total */2300
                                                    ],
                                                    /* :: */[
                                                      /* record */[
                                                        /* sku */"cheese",
                                                        /* productName */"test",
                                                        /* taxRate */15,
                                                        /* salePrice */500,
                                                        /* quantity */2,
                                                        /* subTotal */1000,
                                                        /* tax */150,
                                                        /* total */1150
                                                      ],
                                                      /* :: */[
                                                        /* record */[
                                                          /* sku */"bread",
                                                          /* productName */"test",
                                                          /* taxRate */10,
                                                          /* salePrice */1000,
                                                          /* quantity */2,
                                                          /* subTotal */2000,
                                                          /* tax */200,
                                                          /* total */2200
                                                        ],
                                                        /* [] */0
                                                      ]
                                                    ]
                                                  ]
                                                ], Jest.Expect[/* expect */0](groupedSales));
                                    }));
                      }));
                return /* () */0;
              }));
        return /* () */0;
      }));

exports.buildSale = buildSale;
/*  Not a pure module */
