// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/lib/js/src/jest.js");
var List = require("bs-platform/lib/js/list.js");
var Product = require("./Product.js");

function buildProduct(name, tags) {
  return /* record */[
          /* id */"123",
          /* sku */"123",
          /* name */name,
          /* tags */tags,
          /* department */"dept",
          /* suggestedPrice */1000,
          /* onHand */0,
          /* taxCalculation : Exempt */0
        ];
}

describe("product related utilities", (function () {
        describe("js obj mapping", (function () {
                return Jest.test("it should be able to map an existing product from js", (function () {
                              var js = {
                                _id: "982f1879-c98c-441a-8149-ba6282e8db58",
                                _rev: "1-cb789488740c442cba15653323c005bb",
                                sku: "fasdf",
                                name: "fasdf",
                                department: "dept",
                                onHand: 0,
                                suggestedPrice: 3543534,
                                tags: /* :: */[
                                  "fsdafsda",
                                  /* [] */0
                                ],
                                taxCalculation: "exempt|"
                              };
                              var product = Product.mapFromJs(js);
                              return Jest.Expect[/* toEqual */12](js._id, Jest.Expect[/* expect */0](product[/* id */0]));
                            }));
              }));
        return /* () */0;
      }));

describe("product data functions", (function () {
        describe("filtering products by tag", (function () {
                return Jest.test("it should return only relevant products", (function () {
                              var result = Product.filterProducts("a", /* :: */[
                                    /* record */[
                                      /* id */"123",
                                      /* sku */"123",
                                      /* name */"plate",
                                      /* tags : :: */[
                                        "a",
                                        /* [] */0
                                      ],
                                      /* department */"dept",
                                      /* suggestedPrice */1000,
                                      /* onHand */0,
                                      /* taxCalculation : Exempt */0
                                    ],
                                    /* :: */[
                                      /* record */[
                                        /* id */"123",
                                        /* sku */"123",
                                        /* name */"platter",
                                        /* tags : :: */[
                                          "b",
                                          /* [] */0
                                        ],
                                        /* department */"dept",
                                        /* suggestedPrice */1000,
                                        /* onHand */0,
                                        /* taxCalculation : Exempt */0
                                      ],
                                      /* :: */[
                                        /* record */[
                                          /* id */"123",
                                          /* sku */"123",
                                          /* name */"bowl",
                                          /* tags : :: */[
                                            "a",
                                            /* [] */0
                                          ],
                                          /* department */"dept",
                                          /* suggestedPrice */1000,
                                          /* onHand */0,
                                          /* taxCalculation : Exempt */0
                                        ],
                                        /* [] */0
                                      ]
                                    ]
                                  ]);
                              return Jest.Expect[/* toEqual */12](/* :: */[
                                          /* record */[
                                            /* id */"123",
                                            /* sku */"123",
                                            /* name */"plate",
                                            /* tags : :: */[
                                              "a",
                                              /* [] */0
                                            ],
                                            /* department */"dept",
                                            /* suggestedPrice */1000,
                                            /* onHand */0,
                                            /* taxCalculation : Exempt */0
                                          ],
                                          /* :: */[
                                            /* record */[
                                              /* id */"123",
                                              /* sku */"123",
                                              /* name */"bowl",
                                              /* tags : :: */[
                                                "a",
                                                /* [] */0
                                              ],
                                              /* department */"dept",
                                              /* suggestedPrice */1000,
                                              /* onHand */0,
                                              /* taxCalculation : Exempt */0
                                            ],
                                            /* [] */0
                                          ]
                                        ], Jest.Expect[/* expect */0](result));
                            }));
              }));
        describe("getting only unique tags", (function () {
                return Jest.test("it should return a list of unique tags", (function () {
                              var result = Product.getTags(/* :: */[
                                    /* record */[
                                      /* id */"123",
                                      /* sku */"123",
                                      /* name */"coffee",
                                      /* tags : :: */[
                                        "a",
                                        /* [] */0
                                      ],
                                      /* department */"dept",
                                      /* suggestedPrice */1000,
                                      /* onHand */0,
                                      /* taxCalculation : Exempt */0
                                    ],
                                    /* :: */[
                                      /* record */[
                                        /* id */"123",
                                        /* sku */"123",
                                        /* name */"latte",
                                        /* tags : :: */[
                                          "b",
                                          /* [] */0
                                        ],
                                        /* department */"dept",
                                        /* suggestedPrice */1000,
                                        /* onHand */0,
                                        /* taxCalculation : Exempt */0
                                      ],
                                      /* :: */[
                                        /* record */[
                                          /* id */"123",
                                          /* sku */"123",
                                          /* name */"macchiato",
                                          /* tags : :: */[
                                            "a",
                                            /* [] */0
                                          ],
                                          /* department */"dept",
                                          /* suggestedPrice */1000,
                                          /* onHand */0,
                                          /* taxCalculation : Exempt */0
                                        ],
                                        /* :: */[
                                          /* record */[
                                            /* id */"123",
                                            /* sku */"123",
                                            /* name */"white",
                                            /* tags : :: */[
                                              "c",
                                              /* :: */[
                                                "d",
                                                /* :: */[
                                                  "a",
                                                  /* [] */0
                                                ]
                                              ]
                                            ],
                                            /* department */"dept",
                                            /* suggestedPrice */1000,
                                            /* onHand */0,
                                            /* taxCalculation : Exempt */0
                                          ],
                                          /* :: */[
                                            /* record */[
                                              /* id */"123",
                                              /* sku */"123",
                                              /* name */"black",
                                              /* tags : :: */[
                                                "b",
                                                /* [] */0
                                              ],
                                              /* department */"dept",
                                              /* suggestedPrice */1000,
                                              /* onHand */0,
                                              /* taxCalculation : Exempt */0
                                            ],
                                            /* :: */[
                                              /* record */[
                                                /* id */"123",
                                                /* sku */"123",
                                                /* name */"au lait",
                                                /* tags : :: */[
                                                  "a",
                                                  /* [] */0
                                                ],
                                                /* department */"dept",
                                                /* suggestedPrice */1000,
                                                /* onHand */0,
                                                /* taxCalculation : Exempt */0
                                              ],
                                              /* [] */0
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]);
                              Jest.Expect[/* toBe */2](4, Jest.Expect[/* expect */0](List.length(result)));
                              return Jest.Expect[/* toEqual */12](/* :: */[
                                          "a",
                                          /* :: */[
                                            "b",
                                            /* :: */[
                                              "c",
                                              /* :: */[
                                                "d",
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ], Jest.Expect[/* expect */0](result));
                            }));
              }));
        return /* () */0;
      }));

exports.buildProduct = buildProduct;
/*  Not a pure module */
