// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function toJs(p) {
  return {
          on: p[/* on */0],
          by: p[/* by */1]
        };
}

function fromJs(p) {
  return /* record */[
          /* on */p.on,
          /* by */p.by
        ];
}

exports.toJs = toJs;
exports.fromJs = fromJs;
/* No side effect */
