// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Tax = require("./Tax.js");
var List = require("bs-platform/lib/js/list.js");

function listOfSales(order) {
  return List.map((function (o) {
                return /* record */[
                        /* sku */o[/* sku */0],
                        /* salePrice */o[/* salePrice */4],
                        /* productName */o[/* name */1],
                        /* taxRate */Tax.toTaxRate(o[/* taxCalculation */5]),
                        /* suggestedPrice */o[/* suggestedPrice */2],
                        /* discounts */order[/* discounts */4]
                      ];
              }), order[/* orderItems */3]);
}

exports.listOfSales = listOfSales;
/* No side effect */
