// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");

function toList(tagString) {
  return List.map((function (s) {
                return s.trim();
              }), List.filter((function (s) {
                      return +(s !== "");
                    }))($$Array.to_list(tagString.split(","))));
}

function toCSV(tags) {
  return $$Array.of_list(tags).join(",");
}

exports.toList = toList;
exports.toCSV = toCSV;
/* No side effect */
