// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/lib/js/src/jest.js");
var Tags = require("./Tags.js");

describe("Tag utilities", (function () {
        describe("converting tags", (function () {
                Jest.test("from valid string to list", (function () {
                        return Jest.Expect[/* toEqual */12](/* :: */[
                                    "mickey",
                                    /* :: */[
                                      "mouse",
                                      /* :: */[
                                        "donald",
                                        /* :: */[
                                          "duck",
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ], Jest.Expect[/* expect */0](Tags.toList("mickey,mouse,donald,duck")));
                      }));
                Jest.test("from invalid string to list", (function () {
                        return Jest.Expect[/* toEqual */12](/* :: */[
                                    "mickey",
                                    /* :: */[
                                      "mouse|donald",
                                      /* :: */[
                                        "duck",
                                        /* [] */0
                                      ]
                                    ]
                                  ], Jest.Expect[/* expect */0](Tags.toList("mickey,,mouse|donald,duck,")));
                      }));
                Jest.test("from string with extra spaces to list", (function () {
                        return Jest.Expect[/* toEqual */12](/* :: */[
                                    "mickey",
                                    /* :: */[
                                      "mouse",
                                      /* :: */[
                                        "donald",
                                        /* :: */[
                                          "duck",
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ], Jest.Expect[/* expect */0](Tags.toList("mickey,  mouse,donald  ,duck,")));
                      }));
                return Jest.test("from empty string to empty list", (function () {
                              return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](Tags.toList("")));
                            }));
              }));
        return /* () */0;
      }));

/*  Not a pure module */
