// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function stripLeadingZeros(n) {
  return n.replace((/^0+/), "");
}

function cleanNonNumeric(n) {
  return n.replace((/\D/g), "");
}

function get(key, q) {
  var queryStrToPairs = function (queryStr) {
    var splits = queryStr.split("&");
    return splits.reduce((function (result, str) {
                  var match = str.split("=");
                  var len = match.length;
                  var pair;
                  if (len >= 3) {
                    pair = /* None */0;
                  } else {
                    switch (len) {
                      case 0 : 
                          pair = /* None */0;
                          break;
                      case 1 : 
                          var k = match[0];
                          var p = /* tuple */[
                            k,
                            ""
                          ];
                          pair = /* Some */[p];
                          break;
                      case 2 : 
                          var k$1 = match[0];
                          var v = match[1];
                          var p$1 = /* tuple */[
                            k$1,
                            v
                          ];
                          pair = /* Some */[p$1];
                          break;
                      
                    }
                  }
                  if (pair) {
                    result.push(pair[0]);
                    return result;
                  } else {
                    return result;
                  }
                }), /* array */[]);
  };
  var key$1 = key;
  var qArr = queryStrToPairs(q);
  var pair = qArr.find((function (param) {
          if (param[0] === key$1) {
            return +(param[1] !== "");
          } else {
            return /* false */0;
          }
        }));
  if (pair !== undefined) {
    return /* Some */[pair[1]];
  } else {
    return /* None */0;
  }
}

var QueryParam = /* module */[/* get */get];

exports.stripLeadingZeros = stripLeadingZeros;
exports.cleanNonNumeric = cleanNonNumeric;
exports.QueryParam = QueryParam;
/* No side effect */
