// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function toJs(vendor) {
  return {
          name: vendor[/* name */0]
        };
}

var New = /* module */[/* toJs */toJs];

function fromJs(vendorJs) {
  return /* record */[
          /* id */vendorJs._id,
          /* name */vendorJs.name
        ];
}

function toJsWithRev(id, rev, vendor) {
  return {
          _id: id,
          _rev: rev,
          name: vendor[/* name */1]
        };
}

function toJs$1(vendor) {
  return {
          _id: vendor[/* id */0],
          name: vendor[/* name */1]
        };
}

exports.New = New;
exports.fromJs = fromJs;
exports.toJsWithRev = toJsWithRev;
exports.toJs = toJs$1;
/* No side effect */
