// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function toString() {
  return "Order";
}

function toSource() {
  return /* Order */0;
}

function toJs(webhook) {
  return {
          name: webhook[/* name */0],
          url: webhook[/* url */1],
          event: webhook[/* event */2],
          source: "Order",
          updateSource: webhook[/* updateSource */4]
        };
}

var New = /* module */[/* toJs */toJs];

function fromJs(webhookJs) {
  return /* record */[
          /* id */webhookJs._id,
          /* name */webhookJs.name,
          /* source */(webhookJs.source, /* Order */0),
          /* url */webhookJs.url,
          /* event */webhookJs.event,
          /* updateSource */webhookJs.updateSource
        ];
}

function toJsWithRev(id, rev, webhook) {
  return {
          _id: id,
          _rev: rev,
          name: webhook[/* name */1],
          url: webhook[/* url */3],
          event: webhook[/* event */4],
          source: "Order",
          updateSource: webhook[/* updateSource */5]
        };
}

function toJs$1(webhook) {
  return {
          _id: webhook[/* id */0],
          name: webhook[/* name */1],
          url: webhook[/* url */3],
          event: webhook[/* event */4],
          source: "Order",
          updateSource: webhook[/* updateSource */5]
        };
}

exports.toString = toString;
exports.toSource = toSource;
exports.New = New;
exports.fromJs = fromJs;
exports.toJsWithRev = toJsWithRev;
exports.toJs = toJs$1;
/* No side effect */
