// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function toString(e) {
  switch (e) {
    case 0 : 
        return "BeforeOrderPaid";
    case 1 : 
        return "OrderPaid";
    case 2 : 
        return "OrderReturned";
    case 3 : 
        return "ReprintReceipt";
    case 4 : 
        return "PrintOrder";
    case 5 : 
        return "Error";
    case 6 : 
        return "Unrecognized";
    
  }
}

function toT(e) {
  switch (e) {
    case "BeforeOrderPaid" : 
        return /* BeforeOrderPaid */0;
    case "Error" : 
        return /* Error */5;
    case "OrderPaid" : 
        return /* OrderPaid */1;
    case "OrderReturned" : 
        return /* OrderReturned */2;
    case "PrintOrder" : 
        return /* PrintOrder */4;
    case "ReprintReceipt" : 
        return /* ReprintReceipt */3;
    default:
      return /* Unrecognized */6;
  }
}

var EventType = /* module */[
  /* toString */toString,
  /* toT */toT
];

function toString$1(s) {
  if (s !== 0) {
    return "Unrecognized";
  } else {
    return "Order";
  }
}

function toT$1(s) {
  if (s === "Order") {
    return /* Order */0;
  } else {
    return /* Unrecognized */1;
  }
}

var EventSource = /* module */[
  /* toString */toString$1,
  /* toT */toT$1
];

function toString$2(b) {
  if (b !== 0) {
    return "AwaitResponse";
  } else {
    return "FireAndForget";
  }
}

function fromString(s) {
  if (s === "AwaitResponse") {
    return /* AwaitResponse */1;
  } else {
    return /* FireAndForget */0;
  }
}

var Behavior = /* module */[
  /* toString */toString$2,
  /* fromString */fromString
];

function toJs(webhook) {
  return {
          name: webhook[/* name */0],
          url: webhook[/* url */1],
          event: toString(webhook[/* event */2]),
          source: toString$1(webhook[/* source */3]),
          behavior: toString$2(webhook[/* behavior */4])
        };
}

var New = /* module */[/* toJs */toJs];

function fromJs(webhookJs) {
  return /* record */[
          /* id */webhookJs._id,
          /* name */webhookJs.name,
          /* source */toT$1(webhookJs.source),
          /* url */webhookJs.url,
          /* event */toT(webhookJs.event),
          /* behavior */fromString(webhookJs.behavior)
        ];
}

function toJsWithRev(id, rev, webhook) {
  return {
          _id: id,
          _rev: rev,
          name: webhook[/* name */1],
          url: webhook[/* url */3],
          event: toString(webhook[/* event */4]),
          source: toString$1(webhook[/* source */2]),
          behavior: toString$2(webhook[/* behavior */5])
        };
}

function toJs$1(webhook) {
  return {
          _id: webhook[/* id */0],
          name: webhook[/* name */1],
          url: webhook[/* url */3],
          event: toString(webhook[/* event */4]),
          source: toString$1(webhook[/* source */2]),
          behavior: toString$2(webhook[/* behavior */5])
        };
}

exports.EventType = EventType;
exports.EventSource = EventSource;
exports.Behavior = Behavior;
exports.New = New;
exports.fromJs = fromJs;
exports.toJsWithRev = toJsWithRev;
exports.toJs = toJs$1;
/* No side effect */
